Fix rebatch bar
analysiscenter/batchflow pull request #498
Opened 2020-04-10 18:20 UTC by AlexeyKozhevin

2020-04-28 13:30 UTC, roman-kh commented
This will conflict with #504

2020-08-20 14:00 UTC, roman-kh commented
@AlexeyKozhevin  Fix conflicts, please

2020-09-21 03:47 UTC, roman-kh commented
@AlexeyKozhevin

2020-11-19 15:25 UTC, roman-kh commented
@AlexeyKozhevin Fix the conflict or delete the PR

2020-11-24 18:05 UTC, AlexeyKozhevin commented
Update PR:

- add `total` parameter for the number of resulting batches if you are using `rebatch`
- fix `Notifier` update in case of using `prefetch`

2020-11-25 12:49 UTC, roman-kh requested changes

2020-11-25 12:49 UTC, roman-kh commented on batchflow/pipeline.py
> +        total = kwargs.pop('total', None)
Let's issue a deprecated warning if `bar` is passed.

2020-11-25 12:49 UTC, roman-kh commented on batchflow/pipeline.py
> +        total = kwargs.pop('total', None)
Please, also fix notifier init - it creates DummyBar on else clause. The better behaviour would be to create DummyBar on None and issue a warning for unknown  value.

2021-01-27 16:15 UTC, SergeyTsimfer approved these changes

2021-01-28 10:03 UTC, merged