Pytorch visualizations
analysiscenter/batchflow pull request #530
Opened 2020-10-21 17:35 UTC by SergeyTsimfer

This PR proposes to add visualizations of:

- intermediate activations
![image](https://user-images.githubusercontent.com/47103382/96755844-e4a95400-13db-11eb-8556-c4723fba37bb.png)

- intermediate layers
![image](https://user-images.githubusercontent.com/47103382/96756123-48338180-13dc-11eb-9453-75f3a93ed213.png)

- model attention via [GradCam](https://arxiv.org/pdf/1610.02391.pdf)
![image](https://user-images.githubusercontent.com/47103382/96756537-dad42080-13dc-11eb-8795-01dc4625144b.png)

2020-10-22 08:45 UTC, SergeyTsimfer commented
A slight change to GradCam: now it allows us to pass any tensor to backpropagate from, for example, the true labels. This way we can get this image for seismic related tasks:
![image](https://user-images.githubusercontent.com/47103382/96847605-1104b500-145c-11eb-9f67-3ac9ba59af1b.png)

2020-10-23 12:39 UTC, roman-kh requested changes

2020-10-23 12:39 UTC, roman-kh commented on batchflow/models/torch/base.py
> +        if len(feed_dict) == 1:
Add some comments on what's going on here

2020-10-23 12:39 UTC, roman-kh commented on batchflow/models/torch/base.py
> +        """ Parse arguments to create valid inputs for the model. """
Extend the docstring with examples of inputs and parsing results

2020-10-23 12:39 UTC, roman-kh commented on batchflow/models/torch/base.py
> +    def information(self, config=True, devices=True, train_steps=True, model=False, misc=False):
Make it as clean as possible. It should gather info into a readable structure and print only if needed (or no print at all)

2020-10-23 12:39 UTC, roman-kh commented on batchflow/models/torch/base.py
> +        self.information()
Property should not print!

2020-10-23 12:39 UTC, roman-kh commented on batchflow/models/torch/base.py
> +    def get_intermediate_activations(self, *args, layers=None, feed_dict=None, **kwargs):
These are lo-o-o-ong methods and perhaps can be moved to a separate module

2020-10-29 06:02 UTC, roman-kh commented on batchflow/models/torch/visualization.py
> +""" !!. """
??

2020-11-02 08:32 UTC, merged