Lightning Fast
analysiscenter/batchflow pull request #532
Opened 2020-10-22 17:24 UTC by SergeyTsimfer

This PR proposes to add:

- converter from `Pipeline` to `torch.DataLoader` to make it fully compatible with `torch`  features

- converted from `TorchModel` to `pytorch_lightning.LightningModule` so it can enjoy these features as well

2020-10-23 12:29 UTC, roman-kh requested changes

2020-10-23 12:29 UTC, roman-kh commented on batchflow/models/torch/base.py
> +        if LightningModule == object:
Why not `None`?

2020-10-23 12:29 UTC, roman-kh commented on batchflow/pipeline.py
> +class PipelineDataset(IterableDataset):
Let's move it to a separate module with `torch` in its name

2020-10-23 12:29 UTC, roman-kh commented on batchflow/pipeline.py
> +        return DataLoader(pipeline_dataset, batch_size=None, pin_memory=True, **kwargs)
Make this method one-liner

2020-10-23 12:29 UTC, roman-kh commented on batchflow/models/torch/base.py
> +        images, targets = batch
```suggestion
        inputs, targets = batch
```

2020-10-23 13:01 UTC, nikita-klsh commented
We need to unify optional packages imports across modules and files.

Here you use the block
```
try:
    from pytorch_lightning import LightningModule
except ImportError:
    LightningModule = object
```
And explicitly asking the user to install package in case of absence.

In `monitor.py` there is the block
```
try:
    import nvidia_smi
except ImportError:
    pass
```
And we dont ask to install anything. The `ImportError` implicitly raised in case of `nvidia-smi` absence

2020-10-26 13:58 UTC, anton-br commented on batchflow/pipeline.py
> +        if IterableDataset == object:
what about import error for DataLoader?

2020-10-29 06:16 UTC, roman-kh requested changes

2020-10-29 06:16 UTC, roman-kh commented on batchflow/models/torch/lightning.py
> +>>> dataloader = ppl.to_dataloader('images', 'labels', batch_size=64)
dataloader = pipeline.to_dataloader(batch_size=64, components=['images', 'labels'])

2020-10-29 06:16 UTC, roman-kh commented on batchflow/models/torch/lightning.py
> +>>> lightning_model = batchflow_model.to_lightning()
There is still no way to convert a batchflow model to a custom lightning module class.

2020-10-29 16:47 UTC, anton-br commented on batchflow/models/torch/lightning.py
> +    def __init__(self, dataset, components=None, batch_size=None, pin_memory=True, **kwargs):
add docs about init's arguments

2021-03-20 07:38 UTC, closed without merging