Resnest
analysiscenter/batchflow pull request #544
Opened 2020-12-23 15:13 UTC by anton-br

this pr is adding a model form https://arxiv.org/abs/2004.08955

Fixes #505

2020-12-23 15:48 UTC, SergeyTsimfer reviewed
It is virtually impossoble to read changed files now due to `CodeCov` outputs
@roman-kh is that intended behaviour?
@anton-br please, add notebook (like [this one](https://github.com/analysiscenter/batchflow/blob/master/examples/experiments/self_attention/research_self_attention.ipynb)) to  showcase the model performance with this block

2020-12-23 16:02 UTC, SergeyTsimfer reviewed
Add brief description of the main idea for each block

2020-12-23 16:02 UTC, SergeyTsimfer commented on batchflow/models/torch/blocks.py
> +        layer_params += [{}]*(n_reps-1)
What about the `n_repeats` parameter of `ConvBlock`?

2020-12-23 16:33 UTC, roman-kh commented
> It is virtually impossible to read changed files now due to `CodeCov` outputs
> @roman-kh is that intended behaviour?
I believe this can be changed via codecov configuration file. I've no idea how to do this.

2021-01-19 21:59 UTC, SergeyTsimfer requested changes

2021-01-19 21:59 UTC, SergeyTsimfer commented on batchflow/models/torch/blocks.py
> +    """ ResNeSt Module: pass tensor through one or multiple (`n_reps`) blocks, each of which is a
Make a clear description of what happens to the `input` tensor:

- first of all, we split it into `radix` groups
- then ...
- then apply `sac`
- then ...

2021-01-19 21:59 UTC, SergeyTsimfer commented on batchflow/models/torch/blocks.py
> +    bottleneck_width : int
`reduction_factor` and `bottleneck_width` are actually doing the same: one inside `SAC`, and one inside this block directly.

2021-01-19 21:59 UTC, SergeyTsimfer commented on batchflow/models/torch/blocks.py
> +    attention : str
Should always be `sac`, as it is an essential part of the module

2021-01-19 21:59 UTC, SergeyTsimfer commented on batchflow/models/torch/blocks.py
> +        super().__init__(*layer_params, inputs=inputs, layout=layout, attention=attention,
Remove `strides`

2021-01-19 21:59 UTC, SergeyTsimfer commented on batchflow/models/torch/blocks.py
> +        self_attention = dict(radix=radix, cardinality=cardinality, kernel_size=kernel_size,
```python
attention_kwargs = {
...
}
```

2021-01-19 21:59 UTC, SergeyTsimfer commented on batchflow/models/torch/blocks.py
> +                              external_mult=external_mult)
`external_mult` is actually not used in `sac`. One more reason to remove it

2021-01-19 21:59 UTC, SergeyTsimfer commented on batchflow/models/torch/blocks.py
> +                 strides=1, reduction_factor=1, external_mult=4, bottleneck_width=64, attention='sac', op='+a',
Undocumented `external_mult`, which suddenly changes the amount of desired filters: say, I passed `filters=64`, but for some reason, I get the tensor with `256` channels...

2021-01-19 21:59 UTC, SergeyTsimfer commented on batchflow/models/torch/layers/activations.py
> +    def __init__(self, radix, cardinality, add_dims=0):
Undocumented arguement

2021-01-19 21:59 UTC, SergeyTsimfer commented on batchflow/models/torch/layers/activations.py
> +        if self.add_dims > 0:
Would much rather use `>` letter in the `ConvBlock`

2021-01-19 21:59 UTC, SergeyTsimfer commented on batchflow/models/torch/layers/attention.py
> +        return result.contiguous()
Test if you really need it

2021-01-21 19:20 UTC, SergeyTsimfer approved these changes

2021-01-21 19:20 UTC, SergeyTsimfer commented on batchflow/models/torch/layers/__init__.py
> +from .activation import Activation
`activation` should be before some other stuff, right after `core`

2021-01-21 19:20 UTC, SergeyTsimfer commented on batchflow/models/torch/layers/attention.py
> +    kernel_size : int or list of int
You don't actually need this parameter; `kwargs` can take care of it

2021-01-21 19:20 UTC, SergeyTsimfer commented on batchflow/models/torch/layers/conv_block.py
> +            for i, (key, value) in enumerate(self.items()):
Don't include that into PR

2021-01-21 19:20 UTC, SergeyTsimfer commented on batchflow/models/torch/blocks.py
> +    """ ResNeSt Module: pass tensor through one or multiple (`n_reps`) blocks, each of which is processed the input
`ResNeSt Module: apply following operations to a supplied tensor:`

2021-01-21 19:20 UTC, SergeyTsimfer commented on batchflow/models/torch/blocks.py
> +    * First of all, it goes through 1x1 convolution with normalization and activation.
Missing indentation level

2021-01-21 19:20 UTC, SergeyTsimfer commented on batchflow/models/torch/blocks.py
> +    * Then `sac` is applied:
`Split Attention Convolution`

2021-01-21 19:20 UTC, SergeyTsimfer commented on batchflow/models/torch/blocks.py
> +    The implementation was inspired by the authors' code (`<https://github.com/zhanghang1989/ResNeSt>`_), thus
`is inspired`

2021-01-22 13:37 UTC, SergeyTsimfer approved these changes

2021-02-19 14:39 UTC, merged