Signal propagation plot
analysiscenter/batchflow pull request #577
Opened 2021-04-09 15:28 UTC by RisaMagpie

2021-04-12 10:27 UTC, SergeyTsimfer requested changes

2021-04-12 10:27 UTC, SergeyTsimfer commented on batchflow/models/torch/visualization.py
> +            hooks_controller = ModelForwardExtractor(model)
You can definitely re-use the same class with hooks without implementing your own

2021-04-12 10:27 UTC, SergeyTsimfer commented on batchflow/models/torch/visualization.py
> +        modules_instances = []
What is the reason for this list here?
Anyways, you can just make it as an additional key in your dictionary

2021-04-12 10:27 UTC, SergeyTsimfer commented on batchflow/models/torch/visualization.py
> +            avg_ch_squared_mean = torch.mean(torch.mean(tensor, axis=1) ** 2).item()
You can directly append this to stats: that would eliminate the need for strange variable names

2021-04-12 10:27 UTC, SergeyTsimfer commented on batchflow/models/torch/visualization.py
> +            x = range(len(data))
Is that necessary?

2021-04-12 10:27 UTC, SergeyTsimfer commented on batchflow/models/torch/visualization.py
> +            ax.set_xlabel("Number of network unit", fontsize=12)
Network depth?

2021-04-15 07:51 UTC, SergeyTsimfer commented on batchflow/models/torch/visualization.py
> +        input_shape : sequence
You can use the last model input shape

2021-04-15 07:51 UTC, SergeyTsimfer commented on batchflow/models/torch/visualization.py
> +        if model is None:
`model = model or self.model` is enough

2021-04-15 07:51 UTC, SergeyTsimfer commented on batchflow/models/torch/visualization.py
> +                    module_instance = module.__class__.__name__
move this line above and merge two `if` checks

2021-04-15 07:51 UTC, SergeyTsimfer commented on batchflow/models/torch/visualization.py
> +                        extractors.append(LayerExtractor(module))
This is more important than the previous line; also, you've created `extractors` and `signals` in other order. So, move this line up

2021-04-15 07:51 UTC, SergeyTsimfer commented on batchflow/models/torch/visualization.py
> +        input_tensor = kwargs.get('input_tensor')
Don't do that, please

2021-04-15 07:51 UTC, SergeyTsimfer commented on batchflow/models/torch/visualization.py
> +    def show_signal_propagation_plot(self, **kwargs):
Make it `get_signal_propagation_plot`

2021-04-15 07:51 UTC, SergeyTsimfer commented on batchflow/models/torch/visualization.py
> +            ax.set_title(title + " over network units", fontsize=14)
Add `grid` to the plot

2021-04-20 08:03 UTC, SergeyTsimfer approved these changes

2021-04-22 12:57 UTC, roman-kh commented
Status check failed. Fix it before merging.

2021-06-03 09:51 UTC, merged