Time and memory trackers
analysiscenter/batchflow pull request #654
Opened 2022-07-01 11:47 UTC by Anastasiia-prog

added benchmark.py where you can check forward, backward gpu time and memory for your modules

2022-07-03 15:23 UTC, SergeyTsimfer requested changes
Why this is not in `batchflow.models.torch.utils` or somewhere near?

2022-07-03 15:23 UTC, SergeyTsimfer commented on benchmark/benchmark.py
> +class Time_tracker:
That is not how we name classes in `Python`

2022-07-03 15:23 UTC, SergeyTsimfer commented on benchmark/benchmark.py
> +class Time_tracker:
Documentation?

2022-07-03 15:23 UTC, SergeyTsimfer commented on benchmark/benchmark.py
> +    def timer(self):
Why that is not a property? also, `value` is better name in my opinion

2022-07-03 15:23 UTC, SergeyTsimfer commented on benchmark/benchmark.py
> +def get_memory(reset_memory=True, device=None):
Is that needed?

2022-07-03 15:23 UTC, SergeyTsimfer commented on benchmark/benchmark.py
> +def make_initialization_inputs(inputs, device=None):
We already do have similar function

2022-07-03 15:23 UTC, SergeyTsimfer commented on benchmark/benchmark.py
> +def make_initialization_inputs(inputs, device=None):
And actually this one is copied from that other function...

2022-07-03 15:23 UTC, SergeyTsimfer commented on benchmark/benchmark.py
> +def tracker(module, inputs, repeats=300, warmup=40, device=None, track_backward=True, # .py file ???
This naming does not explain virtually anything about this function

2022-07-03 15:23 UTC, SergeyTsimfer commented on benchmark/benchmark.py
> +    """Track module #macs, #parameters, time and memory consumption on forward and backward pass for a given inputs tensor or inputs shape"""
This documentation does not explain how to use it, what different parameters mean, how it works under the hood and which pitfalls it may have

2022-07-03 15:23 UTC, SergeyTsimfer commented on benchmark/benchmark.py
> +    memory_unit_constant = memory_unit_constants[memory_unit]
Think more about newlines, dev-comments and overall sequence of actions in the function

2022-07-06 11:13 UTC, AlexeyKozhevin commented on benchmark/benchmark.py
> +memory_unit_constants = {'GB': 1e-9, 'MB': 1e-6, 'KB': 1e-3, 'B': 1.}
Constant names are in the upper case usually

2022-07-08 12:19 UTC, SergeyTsimfer requested changes

2022-07-08 12:19 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +MEMORY_UNIT_CONSTANTS = {'GB': 1/(1024*1024*1024), 'MB': 1/(1024*1024), 'KB': 1/1024, 'B': 1.}
`1024 ** 3`
dict formatting:
```
dictionary = {
    'key': 'value',
}
```

2022-07-08 12:19 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +    """Track time for operation on gpu."""
```python
""" Measure time taken for an operation on GPU. """
```

2022-07-08 12:19 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +class MemoryTracker:
```python
""" Measure peak used memory for an operation on GPU. """
```

2022-07-08 12:19 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +def get_module_info(module, inputs, repeats=300, warmup=40, device=None, track_backward=True,
`benchmark_module`?
`measure_module_performance`?
`get_module_performance`?

2022-07-08 12:19 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +             Data which enter to the module.
indents

2022-07-08 12:19 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +                  See MEMORY_UNIT_CONSTANTS which units you can choose for memory
this documentation is compiled to a HTML
you will not be able to see any constants

2022-07-08 12:19 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +
why newline

2022-07-08 12:19 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +
why newline

2022-07-08 12:19 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +
why newline

2022-07-08 12:19 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +                del outputs
why `del` here and not anywhere else

2022-07-08 12:19 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +                i += 1
what does this line do

2022-07-08 12:19 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +                torch.cuda.empty_cache()
why? this breaks a lot of things

2022-07-08 12:19 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +                with TimeTracker() as bt:
`as forward_timer`
You really don't need to skimp on variable name lenghts in `Python`

2022-07-08 12:19 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +            module(inputs)
this should be 
```python
outputs = module(inputs)
```

this way, you will be able to use `outputs` in backward tracking block
Also, I'm not even sure that `cuda` performs this operation as it is not blocking

2022-07-08 12:19 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +from ptflops import get_model_complexity_info
this adds a dependency to `batchflow`
we don't want that

2022-07-12 14:13 UTC, SergeyTsimfer requested changes

2022-07-12 14:13 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +        If Tensor, then it is a data which we use for tracking performance.
`If Tensor, then directly used as module input`
`If sequence of ints, then interpreted as shape of a tensor to make. The shape must include batch dimension.`

2022-07-12 14:13 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +        Number of times to repeat forward and backward pass for tracking performance.
`for tracking performance` is really not needed. All of the parameters affect `how we are tracking performance`

2022-07-12 14:13 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +        If str, then any option of device configuration from :class:`torch.nn.Module` is supported.
`Device for computations. Any option of `PyTorch` device configuration is supported.`

2022-07-12 14:13 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +    dict
```python
    dict
        Dictionary with results of measure module performance.
        It contains:
            - number of parameters in the module.
            - MACs. Estimated for `PyTorch` native operations only.
            - forward and backward (if required) statistics:
                - time (mean and std).
                - allocated memory.
            - total time taken for all measurements.
```

2022-07-12 14:13 UTC, SergeyTsimfer commented on batchflow/models/torch/benchmark.py
> +from ptflops import get_model_complexity_info
this still adds a new dependency to `batchflow` and we still don't want that

2022-07-15 09:11 UTC, HollowPrincess requested changes

2022-07-15 09:11 UTC, HollowPrincess commented on batchflow/models/torch/benchmark.py
> +        """ Get total operation time. """
```suggestion
        """ Total operation time. """
```

2022-08-03 12:49 UTC, merged