deformable conv
analysiscenter/batchflow pull request #682
Opened 2022-12-21 17:29 UTC by AnnaAltynova

implemented deformable conv v3

2022-12-22 07:22 UTC, HollowPrincess requested changes
I left little comments, PR looks OK.

2022-12-22 10:28 UTC, AnnaAltynova commented on batchflow/models/torch/layers/multilayer.py
> +        'y': 'deformable_conv2d',
since we don't have much letters left, but any suggestions are welcome :)

2022-12-22 10:51 UTC, SergeyTsimfer reviewed
I would like to have `v2` and `v3` versions. We can do it by having two classes or by having an `if-else` clause on `version` parameter. I do like the second option more, as it would result less code duplication

2022-12-22 10:51 UTC, SergeyTsimfer commented on batchflow/models/torch/layers/conv_complex.py
> +from torch.nn.modules.utils import _pair
I am strongly against using functions from other packages' `utils`, especially ones with underscore in its name: those functions can be changed drastically, and this particular function saves you like 10 characters at most with loss at readability.
Anyhow, there is already a `to_n_tuple` function in `batchflow.models.torch.utils`.

2022-12-22 10:51 UTC, SergeyTsimfer commented on batchflow/models/torch/layers/conv_complex.py
> +    Wang, Wenhai, et al. "`InternImage: Exploring Large-Scale Vision Foundation Models with Deformable Convolutions
I would also add the link to v2 paper

2022-12-22 10:51 UTC, SergeyTsimfer commented on batchflow/models/torch/layers/conv_complex.py
> +    LAYER = nn.Conv2d
As this layer is 2D only (and I doubt that `PyTorch` would add 3D implementation any soon), I would not use this class attribute and just hardcode `Conv2d` calls

2022-12-22 10:51 UTC, SergeyTsimfer commented on batchflow/models/torch/layers/conv_complex.py
> +            raise NotImplementedError("DeformableConv2d supports only 2d inputs.")
...although I would keep this check

2022-12-22 10:51 UTC, SergeyTsimfer commented on batchflow/models/torch/layers/conv_complex.py
> +                                    dilation=dilation, transposed=False, stride=stride))
indent

2022-12-22 10:51 UTC, SergeyTsimfer commented on batchflow/models/torch/layers/conv_complex.py
> +
too many newlines

2022-12-22 10:51 UTC, SergeyTsimfer commented on batchflow/models/torch/layers/conv_complex.py
> +        self.args.update(compute_padding(padding=padding, shape=inputs.shape[-dims:], kernel_size=kernel_size,
why `[-dims:]`? It should be `[2:]`
While it is numerically the same in case of 2D inputs (4D tensors), it makes no sense otherwise

2022-12-22 10:51 UTC, SergeyTsimfer commented on batchflow/models/torch/layers/conv_complex.py
> +        self.args.update({'out_channels': offset_groups * 2 * kernel_size[0] * kernel_size[1],
I dislike having the same `dict` updated and reused multiple times, especially when it is an instance attribute and supposed to reflect some properties of a layer. Make copies of parameter dicts for `offset` and `modulator` convs

2022-12-22 10:51 UTC, SergeyTsimfer commented on batchflow/models/torch/layers/conv_complex.py
> +        self.args.update({'out_channels': offset_groups * 2 * kernel_size[0] * kernel_size[1],
or dont store it in instance at all. `padding`, `stride` and `dilation` can be retrieved from `depthwise_layer` the same way you get its `weight` and `bias`

2022-12-30 09:10 UTC, SergeyTsimfer approved these changes

2022-12-30 09:11 UTC, merged