fix release
analysiscenter/batchflow pull request #759
Opened 2024-07-24 09:28 UTC by BulatVakhitov

This PR updates the release workflow to implement the trusted publishers workflow as suggested [here](https://docs.pypi.org/trusted-publishers/using-a-publisher/)

2024-07-26 07:54 UTC, roman-kh requested changes

2024-07-26 07:54 UTC, roman-kh commented on .github/workflows/release-check.yml
> +        repository-url: https://test.pypi.org/legacy/
The last line in the file should be empty

2024-07-26 07:54 UTC, roman-kh commented on .github/workflows/release.yml
> +      uses: pypa/gh-action-pypi-publish@release/v1
The last line in the file should be empty

2024-07-29 07:52 UTC, AlexeyKozhevin approved these changes

2024-07-29 08:50 UTC, merged